# Generated by Django 3.0.2 on 2020-02-12 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('breed', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=200)),
                ('age', models.DecimalField(decimal_places=5, max_digits=7)),
                ('weight', models.DecimalField(decimal_places=5, max_digits=8)),
                ('location', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=200)),
                ('status', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PollRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retrievaltime', models.DateTimeField(verbose_name='retrieval time')),
            ],
        ),
    ]
